from __future__ import annotations

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[2]
WORKSPACE_DIR = BASE_DIR / "workspace"
JOBS_DIR = WORKSPACE_DIR / "jobs"
FRONTEND_DIR = BASE_DIR / "frontend"

DEFAULT_DPI = 300
DEFAULT_CHUNK_SIZE = 1800
DEFAULT_RENDER_STRATEGY = "pre_render_all"
DEFAULT_OUTPUT_MODE = "readable"
DEFAULT_DEEPSEEK_OCR_MODEL = "mlx-community/DeepSeek-OCR-2-bf16"
DEFAULT_DEEPSEEK_OCR_MAX_TOKENS = 4096
DEFAULT_DEEPSEEK_OCR_PROMPT = "<image>\n<|grounding|>Convert the document to markdown."
DEFAULT_DEEPSEEK_OCR_CROP_MODE = True
DEFAULT_DEEPSEEK_OCR_MIN_CROPS = 2
DEFAULT_DEEPSEEK_OCR_MAX_CROPS = 6
DEFAULT_DEEPSEEK_OCR_BASE_SIZE = 1024
DEFAULT_DEEPSEEK_OCR_IMAGE_SIZE = 768
DEFAULT_DEEPSEEK_OCR_SKIP_REPEAT = True
DEFAULT_DEEPSEEK_OCR_NGRAM_SIZE = 20
DEFAULT_DEEPSEEK_OCR_NGRAM_WINDOW = 90
DEFAULT_TRANSLATION_MODEL = "mlx-community/Qwen3.5-4B-OptiQ-4bit"
AVAILABLE_TRANSLATION_MODELS = [
    DEFAULT_TRANSLATION_MODEL,
]

for directory in [WORKSPACE_DIR, JOBS_DIR]:
    directory.mkdir(parents=True, exist_ok=True)
